### ISSUE TITLE
Get all clans example is missing some info

### ISSUE THREAD

**Issue by ingridflack** [bautistaaa/narutoQL#13]
The query example "Get all clans" is missing `result`.

It is currently like this:

```graphql
{
  clans {
    name    
    description
    avatarSrc
    village
  }
}
```
And should be like this:
```graphql
{
  clans {
    results {
      name    
      description
      avatarSrc
      village
    }
  }
}
```

**Comment by bautistaaa** [comment]
want to fix the docs 👀

**Comment by ingridflack** [comment]
@bautistaaa Sure! It would be nice, but I didn't find where to do it 😞

**Comment by bautistaaa** [comment]
https://github.com/bautistaaa/narutoQL/blob/b4e5219d8634559b1501a74aa6db9006c900461d/src/client/components/documentation/ClanAll.tsx

Does `Village` have the same problems?

**Comment by ingridflack** [comment]
No, only `Clans` seems to have this issue, but I'll review all the examples in the documentation.

I will create a PR later today. Thanks for the link 😄

**Comment by bautistaaa** [comment]
interesting `Village` should probably follow the same to be consistent. If its not can you file an issue and I can fix (or you can). thanks for using!
